AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Handler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler
      Runtime: go1.x
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hook/{token}/{channel}
            Method: post
Outputs:
  URL:
    Description: URL for HTTPS Endpoint
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: ServerlessRestApi
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com/"
          - Ref: ServerlessRestApiProdStage
