version: 2

defaults: &defaults
  working_directory: /go/src/github.com/sbstjn/github-releases-slack
  docker:
    - image: jimdo/golang-dep

releases: &releases
  filters:
    tags:
      only: /v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Gopkg.toml" }}

      - run:
          name: Install dependencies
          command: make install

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Gopkg.toml" }}
          paths:
            - vendor

      - persist_to_workspace:
          root: .
          paths:
            - fixtures
            - Makefile
            - infrastructure.yml
            - vendor
            - "*.go"

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Run tests
          command: make test

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Build binary
          command: make build

      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy-stable:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy to Stable
          command: ENV=stable make package deploy

  deploy-prod:
    <<: *defaults

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy to Production
          command: ENV=prod make package deploy

workflows:
  version: 2

  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - test
      - deploy-stable:
          filters:
            branches:
              only: master
          requires:
            - build

  release:
    jobs:
      - checkout:
          <<: *releases
      - test:
          <<: *releases
          requires:
            - checkout
      - build:
          <<: *releases
          requires:
            - test
      - deploy-prod:
          <<: *releases
          requires:
            - build
